on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/build.yml'
      - 'src/**'

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6.2.5
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 5.0.3
          mongodb-replica-set: entitydb
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
      - name: Restore Dependencies
        run: dotnet restore src/EntityDb.sln --locked-mode
      - name: Run Project Tests
        run: dotnet test src/EntityDb.sln --no-restore -c Release --collect:"XPlat Code Coverage" -r ./TestResults -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Get Coverage Reports
        id: get_coverage_reports
        run: |
          echo ::set-output name=csv::"'$(ls TestResults/**/*.xml | tr '\n', ',' | rev | cut --complement -c 1 | rev)'"
      - name: Publish Coverage Results
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ steps.get_coverage_reports.outputs.csv }}