on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/build.yml'
      - 'src/**'

name: Build

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
      - name: Restore Dependencies
        run: dotnet restore src\EntityDb.sln --locked-mode
      - name: Run Project Tests
        run: dotnet test src\EntityDb.sln --no-restore -c Release