on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-prerelease'

name: Publish to Nuget.org

jobs:
  version:
    name: Extract Version
    runs-on: ubuntu-latest
    outputs:
      csproj: ${{ steps.csproj.outputs.version }}
    steps:
      - id: csproj
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
        
  nuget:
    name: Publish to Nuget.org
    runs-on: windows-latest
    needs: version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
      - name: Restore Dependencies
        run: dotnet restore --locked-mode
      - name: Run Project Tests
        run: dotnet test --no-restore -c Release
      - name: Pack Projects into Nuget Packages
        run: dotnet pack --no-restore -c Release /p:Version=${{ needs.version.outputs.csproj }}
      - name: Publish Nuget Packages
        run: dotnet nuget push */**.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}