on:
  release:
    types:
      - published

name: Publish to Nuget.org

jobs:
  extract:
    name: Extract Release Information
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      notes: ${{ steps.notes.outputs.notes }}
    steps:
      - id: release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - id: version
        run: echo ::set-output name=version::${steps.release.tag_name#v}
      - id: notes
        run: echo ::set-output name=notes::${steps.release.body}

  nuget:
    name: Publish to Nuget.org
    runs-on: windows-latest
    needs: extract
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
      - name: Restore Dependencies
        run: dotnet restore --locked-mode
      - name: Run Project Tests
        run: dotnet test --no-restore -c Release
      - name: Pack Projects into Nuget Packages
        run: dotnet pack --no-restore -c Release /p:Version=${{ needs.extract.outputs.version }} /p:PackageReleaseNotes=${{ needs.extract.outputs.notes }}
      - name: Publish to Nuget.org
        run: dotnet nuget push */**.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}